import { CommonModule } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { AuthService } from '../../../core/services/auth/auth.service';
import { TeamService } from '../../../core/services/team/team.service';
import { ModalService } from '../../../core/services/modal/modal.service';
import { buildTeamFilterDTOFromSearchBy } from '../../../core/utils/rest-utils';
import { PaginationComponent } from '../../../shared/components/pagination/pagination.component';
import { SearchBarComponent } from '../../../shared/components/search-bar/search-bar.component';
import { ModalType } from '../../../shared/models/modal-type.enum';
import { TeamResponse } from '../models/team-response.model';
import { TeamRequest } from '../models/team-request.model';
import { UserResponse } from '../../profile/models/user-response.model';
import { Role } from '../../profile/models/user-role.enum';

@Component({
  selector: 'app-teams',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    CommonModule,
    SearchBarComponent,
    PaginationComponent
  ],
  templateUrl: './teams.component.html',
  styleUrl: './teams.component.scss'
})
export class TeamsComponent implements OnInit, OnDestroy {

  teams: TeamResponse[] = [];
  loading = false;
  error: string | null = null;
  addTeamForm!: FormGroup;
  showAddForm = false;
  currentPage = 0;
  totalPages = 0;
  currentUser?: UserResponse;
  userSubscription?: Subscription;

  constructor(
    private teamService: TeamService,
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private modalService: ModalService,
    private authService: AuthService
  ) {}

  ngOnInit(): void {
    this.initializeForm();
    this.subscribeToUser();
    this.subscribeToQueryParams();
  }

  ngOnDestroy(): void {
    this.userSubscription?.unsubscribe();
  }

  private initializeForm(): void {
    this.addTeamForm = this.fb.group({
      teamName: [
        '',
        [
          Validators.required,
          Validators.minLength(2),
          Validators.maxLength(50)
        ]
      ],
      description: [
        '',
        [
          Validators.maxLength(255)
        ]
      ]
    });
  }

  private subscribeToUser(): void {
    this.userSubscription = this.authService.user$
      .subscribe(user => {
        this.currentUser = user;
      });
  }

  private subscribeToQueryParams(): void {
    this.route.queryParamMap.subscribe(params => {
      const searchBy = params.get('searchBy') ?? '';
      this.currentPage = +(params.get('page') ?? '0');
      this.fetchTeams(searchBy, this.currentPage);
    });
  }

  private fetchTeams(searchBy: string, page: number): void {
    this.loading = true;
    this.error = null;

    const filter = buildTeamFilterDTOFromSearchBy(searchBy, page);

    this.teamService.getAll(filter).subscribe({
      next: (response) => {
        this.teams = response.elements;
        this.totalPages = response.totalPages;
        this.loading = false;
      },
      error: (error: HttpErrorResponse) => {
        this.error = 'Failed to load teams: ' + (error.error?.message || error.message);
        this.loading = false;
        console.error('Error loading teams:', error);
      }
    });
  }

  toggleAddForm(): void {
    this.showAddForm = !this.showAddForm;
    if (this.showAddForm) {
      this.addTeamForm.reset();
    }
  }

  cancelAdd(): void {
    this.showAddForm = false;
    this.addTeamForm.reset();
  }

  saveTeam(): void {
    if (this.addTeamForm.invalid) {
      this.addTeamForm.markAllAsTouched();
      return;
    }

    this.loading = true;
    const teamData: TeamRequest = {
      id: '', // Will be generated by backend
      teamName: this.addTeamForm.value.teamName,
      description: this.addTeamForm.value.description || ''
    };

    this.teamService.save(teamData).subscribe({
      next: (savedTeam) => {
        this.teams.unshift(savedTeam); // Add to beginning of list
        this.addTeamForm.reset();
        this.showAddForm = false;
        this.loading = false;
        this.modalService.open('Success', 'Team has been successfully created!', ModalType.SUCCESS);
      },
      error: (error: HttpErrorResponse) => {
        this.loading = false;
        const errorMessage = error.error?.message || 'Failed to create team';
        this.modalService.open('Error', errorMessage, ModalType.ERROR);
        console.error('Error creating team:', error);
      }
    });
  }

  editTeam(team: TeamResponse): void {
    // Navigate to team edit page
    // You can implement this based on your routing setup
    console.log('Edit team:', team);
  }

  confirmDeleteTeam(team: TeamResponse): void {
    this.modalService.open(
      'Delete Team',
      `Are you sure you want to delete the team "${team.teamName}"? This action cannot be undone.`,
      ModalType.CONFIRM
    );

    // Subscribe to confirmation
    this.modalService.confirm$.subscribe(() => {
      this.deleteTeam(team);
    });
  }

  private deleteTeam(team: TeamResponse): void {
    this.teamService.delete(team.id).subscribe({
      next: () => {
        this.teams = this.teams.filter(t => t.id !== team.id);
        this.modalService.open('Success', 'Team has been successfully deleted.', ModalType.SUCCESS);
      },
      error: (error: HttpErrorResponse) => {
        const errorMessage = error.error?.message || 'Failed to delete team';
        this.modalService.open('Error', errorMessage, ModalType.ERROR);
        console.error('Error deleting team:', error);
      }
    });
  }

  refreshTeams(): void {
    const currentParams = this.route.snapshot.queryParamMap;
    const searchBy = currentParams.get('searchBy') ?? '';
    this.fetchTeams(searchBy, this.currentPage);
  }

  onPageChange(page: number): void {
    this.currentPage = page;
    const currentParams = this.route.snapshot.queryParamMap;
    const searchBy = currentParams.get('searchBy') ?? '';
    this.fetchTeams(searchBy, page);
  }

  // Permission checks
  canEditTeam(): boolean {
    return this.currentUser?.role === Role.ADMIN ||
      this.currentUser?.role === Role.PROJECT_MANAGER;
  }

  canDeleteTeam(): boolean {
    return this.currentUser?.role === Role.ADMIN;
  }

  canCreateTeam(): boolean {
    return this.currentUser?.role === Role.ADMIN ||
      this.currentUser?.role === Role.PROJECT_MANAGER;
  }
}
